# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  [![Welcome Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:8ff47a85-7250-4d86-8e48-2f346b48b2c1:BannerWelcome.jpg/full/750,/0/default.jpg)](https://zenodo.org/record/3695300)

  :tada: Welcome to _PyMC_! :tada:
  We're really excited to have your input into the project! :sparkling_heart:

  <br>If you haven't done so already, please make sure you check out our [Contributing Guidelines](https://www.pymc.io/projects/docs/en/latest/contributing/index.html) and [Code of Conduct](https://github.com/pymc-devs/pymc/blob/main/CODE_OF_CONDUCT.md).


# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  [![Thank You Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:7fbd97cf-283b-480c-b8e1-11866e26245c:BannerThanks.jpg/full/750,/0/default.jpg)](https://zenodo.org/record/3695300)

  :sparkling_heart: Thanks for opening this pull request! :sparkling_heart:
  The _PyMC_ community really appreciates your time and effort to contribute to the project.
  Please make sure you have read our [Contributing Guidelines](https://www.pymc.io/projects/docs/en/latest/contributing/index.html) and filled in our pull request template to the best of your ability.


# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  [![Congratulations Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:32fbdb89-ae1b-434e-830c-88ade86724cc:BannerCongratulations.jpg/full/750,/0/default.jpg)](https://zenodo.org/record/3695300)

  Congrats on merging your first pull request! :tada:
  We here at _PyMC_ are proud of you! :sparkling_heart:
  Thank you so much for your contribution :gift:
