site_name: PyMC3
repo_url: https://github.com/pymc-devs/pymc3
site_author: PyMC devs
markdown_extensions: ['extra', 'mathjax']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']

pages:
- Overview: 'index.md'
- Tutorial:
  - 'Getting started': 'getting_started.md'
- Examples:
  - 'BEST': 'BEST.md'
  - 'Stochastic Volatility': 'stochastic_volatility.md'
  - 'Hierarchical model': 'hierarchical.md'
  - 'Linear Regression': 'GLM-linear.md'
  - 'Robust Regression': 'GLM-robust.md'
  - 'Robust Regression with Outlier Detection': 'GLM-robust-with-outlier-detection.md'
  - 'Hierarchical linear regression': 'GLM-hierarchical.md'
  - 'Probabilistic Matrix Factorization': 'pmf-pymc.md'
  - 'Rugby Analytics example': 'rugby_analytics.md'
  - 'Posterior Predictive checks and prediction': 'posterior_predictive.md'
  - 'Survival Analysis': 'survival_analysis.md'
  - 'Gaussian Process (GP) smoothing': 'GP-smoothing.md'
