# "test" conda envs are used to set up our CI environment in GitHub actions
name: pymc-test
channels:
- conda-forge
- nodefaults
dependencies:
# Base dependencies
- arviz>=0.13.0
- arviz-base>=0.7.0
- blas
- cachetools>=4.2.1
- cloudpickle
- zarr>=2.5.0,<3
- numba
- nutpie >= 0.15.1
# Jaxlib version must not be greater than jax version!
- blackjax>=1.2.2
- jax>=0.4.28
- jaxlib>=0.4.28
- libblas=*=*mkl
- mkl-service
- numpy>=1.25.0
- numpyro>=0.8.0
- pandas>=0.24.0
- pip
- pytensor>=2.36.2,<2.37
- python-graphviz
- networkx
- rich>=13.7.1
- threadpoolctl>=3.1.0
# JAX is only compatible with Scipy 1.13.0 from >=0.4.26
- scipy>=1.13.0
- typing-extensions>=3.7.4
# Extra dependencies for testing
- ipython>=7.16
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- mypy=1.19.1
- types-cachetools
- pip:
  - numdifftools>=0.9.40
  - mcbackend>=0.4.0
