# "test" conda envs are used to set up our CI environment in GitHub actions
name: pymc-test
channels:
- conda-forge
- nodefaults
dependencies:
# Base dependencies
- arviz>=0.13.0
- blas
- cachetools>=4.2.1
- cloudpickle
- jax
- numpy>=1.25.0
- pandas>=0.24.0
- pip
- polyagamma
- pytensor>=2.37.0,<2.38
- python-graphviz
- networkx
- rich>=13.7.1
- scipy>=1.4.1
- typing-extensions>=3.7.4
- threadpoolctl>=3.1.0
- zarr>=2.5.0,<3
# Extra dependencies for testing
- ipython>=7.16
- preliz>=0.20.0
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- mypy=1.19.1
- types-cachetools
- pip:
  - numdifftools>=0.9.40
  - mcbackend>=0.4.0
