# "test" conda envs are used to set up our CI environment in GitHub actions
name: pymc-test-py37
channels:
- conda-forge
- defaults
dependencies:
- aeppl=0.0.18
- aesara=2.3.8
- arviz>=0.11.4
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py>=2.7
- ipython
- libblas=*=*mkl
- mkl-service
- numpy>=1.15.0
- pandas>=0.24
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- python-graphviz
- python=3.7
- scipy>1.4.1
- typing-extensions
