name: pymc-dev-py38
channels:
- conda-forge
- defaults
dependencies:
 # base dependencies (see install guide for Windows)
- aeppl=0.0.18
- aesara=2.3.8
- arviz>=0.11.4
- cachetools>=4.2.1
- cloudpickle
- fastprogress>=0.2.0
- h5py
- numpy>=1.15.0
- pandas
- pip
- python=3.8
- python-graphviz
- scipy>1.4.1
- typing-extensions>=3.7.4
# Extra stuff for dev, testing and docs build
- ipython
- myst-nb
- numpydoc<1.2
- pre-commit>=2.8.0
- pydata-sphinx-theme
- pytest-cov>=2.5
- pytest>=3.0
- sphinx-autobuild>=0.7
- sphinx-copybutton
- sphinx-notfound-page
- sphinx>=1.5
- watermark
- pip:
  - sphinx-design
  - sphinx-remove-toctrees
