name: devcontainer-docker-image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-devcontainer  # pymc-devs/pymc-devcontainer

jobs:
  build-container:
    runs-on: ubuntu-latest

    # Set permissions for GitHub token
    # <https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#authenticating-to-package-registries-on-github>
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Prepare metadata
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,enable=true,prefix=git-
          type=raw,value=latest

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      with:
        context: .
        file: scripts/dev.Dockerfile
        platforms: linux/amd64  # ,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline
