name: docker-image

on:
  # Commenting for testing purposes
  # release:
  #   types:
  #     - created
  push:
    branches: [fix/gh-docker-image]

env:
  CONTAINER_NAME: build-test

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
              name=pymc/pymc,enable=true
          tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: Build and load image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: scripts/Dockerfile
          load: true
          tags: ${{ env.CONTAINER_NAME }}

      - name: Test importing pymc
        run: |
           docker run --rm ${{ env.CONTAINER_NAME }} conda run -n pymc-dev python -c 'import pymc;print(pymc.__version__)'

      # Commenting for testing purposes
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     file: scripts/Dockerfile
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
