name: mypy

permissions: {}

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-file: conda-envs/environment-test.yml
          create-args: >-
            python=3.11
          environment-name: pymc-test
          init-shell: bash
          cache-environment: true
      - name: Install-pymc and mypy dependencies
        run: |
          pip install -e .
          python --version
      - name: Run mypy
        run: |
          python ./scripts/run_mypy.py --verbose
