name: pytest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        floatx: [float32, float64]
        test-subset:
        # Tests are split into multiple jobs to accelerate the CI.
        # The first job (starting in the next block) shouldn't run any tests, but
        # just ignores tests because that don't work at all, or run in other jobs.'
        # Any test that was not ignored runs in the first job.
        # A pre-commit hook (scripts/check_all_tests_are_covered.py) enforces that
        # test run just once.

        # Because YAML doesn't allow comments in the blocks below, here they are..
        # 1st block: These tests are temporarily disabled, because they are _very_ broken
        # 2nd block: The JAX tests run through their own workflow: jaxtests.yml
        # 3nd & 4rd: These tests are covered by other matrix jobs
        # 5th block: These tests PASS without a single XFAIL
        # 6th block: These have some XFAILs
          - |
            --ignore=pymc3/tests/test_distributions_timeseries.py
            --ignore=pymc3/tests/test_missing.py
            --ignore=pymc3/tests/test_mixture.py
            --ignore=pymc3/tests/test_model_graph.py
            --ignore=pymc3/tests/test_modelcontext.py
            --ignore=pymc3/tests/test_parallel_sampling.py
            --ignore=pymc3/tests/test_profile.py
            --ignore=pymc3/tests/test_random.py
            --ignore=pymc3/tests/test_shared.py
            --ignore=pymc3/tests/test_smc.py
            --ignore=pymc3/tests/test_starting.py
            --ignore=pymc3/tests/test_step.py
            --ignore=pymc3/tests/test_tracetab.py
            --ignore=pymc3/tests/test_tuning.py
            --ignore=pymc3/tests/test_types.py
            --ignore=pymc3/tests/test_variational_inference.py
            --ignore=pymc3/tests/test_sampling_jax.py
            --ignore=pymc3/tests/test_dist_math.py
            --ignore=pymc3/tests/test_minibatches.py
            --ignore=pymc3/tests/test_pickling.py
            --ignore=pymc3/tests/test_plots.py
            --ignore=pymc3/tests/test_special_functions.py
            --ignore=pymc3/tests/test_updates.py
            --ignore=pymc3/tests/test_examples.py
            --ignore=pymc3/tests/test_glm.py
            --ignore=pymc3/tests/test_glm_utils.py
            --ignore=pymc3/tests/test_glm_linear.py
            --ignore=pymc3/tests/test_gp.py
            --ignore=pymc3/tests/test_model.py
            --ignore=pymc3/tests/test_model_func.py
            --ignore=pymc3/tests/test_ode.py
            --ignore=pymc3/tests/test_posdef_sym.py
            --ignore=pymc3/tests/test_quadpotential.py
            --ignore=pymc3/tests/test_shape_handling.py
            --ignore=pymc3/tests/test_distributions.py
            --ignore=pymc3/tests/test_distributions_random.py
            --ignore=pymc3/tests/test_idata_conversion.py

          - |
            pymc3/tests/test_modelcontext.py
            pymc3/tests/test_dist_math.py
            pymc3/tests/test_minibatches.py
            pymc3/tests/test_pickling.py
            pymc3/tests/test_plots.py
            pymc3/tests/test_special_functions.py
            pymc3/tests/test_updates.py

          - |
            pymc3/tests/test_idata_conversion.py
            pymc3/tests/test_distributions.py
            pymc3/tests/test_distributions_random.py
            pymc3/tests/test_examples.py
            pymc3/tests/test_glm.py
            pymc3/tests/test_glm_utils.py
            pymc3/tests/test_gp.py
            pymc3/tests/test_model.py
            pymc3/tests/test_model_func.py
            pymc3/tests/test_ode.py
            pymc3/tests/test_posdef_sym.py
            pymc3/tests/test_quadpotential.py
            pymc3/tests/test_shape_handling.py
            pymc3/tests/test_step.py

      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment-dev-py37.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-dev-py37.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pymc3-dev-py37
          channel-priority: strict
          environment-file: conda-envs/environment-dev-py37.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc3
        run: |
          conda activate pymc3-dev-py37
          pip install -e .
          python --version
      - name: Run tests
        run: |
          conda activate pymc3-dev-py37
          python -m pytest -vv --cov=pymc3 --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
