name: tests

on:
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "pymc/**.py"
      - "*.py"
      - "conda-envs/**"
      - "codecov.yml"
      - "requirements*.txt"
      - "scripts/*.sh"
  push:
    branches: [main]
    paths:
      - ".github/workflows/tests.yml"
      - "pymc/**.py"
      - "*.py"
      - "conda-envs/**"
      - "codecov.yml"
      - "scripts/*.sh"

# Tests are split into multiple jobs to accelerate the CI.
# Different jobs should be organized to take approximately the same
# time to complete (and not be prohibitely slow).
# Because GitHub Actions don't support YAML anchors, we have to place the
# splitting of testfiles into groups in the strategy/matrix/test-subset
# and can't re-use the groups across jobs.
# A pre-commit hook (scripts/check_all_tests_are_covered.py)
# enforces that test run just once per OS / floatX setting.

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        floatx: [float64]
        python-version: ["3.10"]
        test-subset:
          - |
            pymc/tests/test_util.py
            pymc/tests/distributions/test_logprob.py
            pymc/tests/test_aesaraf.py
            pymc/tests/test_math.py
            pymc/tests/backends/test_base.py
            pymc/tests/backends/test_ndarray.py
            pymc/tests/step_methods/hmc/test_hmc.py
            pymc/tests/test_func_utils.py
            pymc/tests/distributions/test_shape_utils.py
            pymc/tests/distributions/test_mixture.py

          - |
            pymc/tests/distributions/test_distribution.py
            pymc/tests/distributions/test_discrete.py
            pymc/tests/distributions/test_continuous.py
            pymc/tests/distributions/test_multivariate.py

          - |
            pymc/tests/distributions/test_bound.py
            pymc/tests/distributions/test_censored.py
            pymc/tests/distributions/test_simulator.py
            pymc/tests/distributions/test_truncated.py
            pymc/tests/sampling/test_forward.py
            pymc/tests/sampling/test_population.py
            pymc/tests/stats/test_convergence.py

          - |
            pymc/tests/tuning/test_scaling.py
            pymc/tests/tuning/test_starting.py
            pymc/tests/distributions/test_dist_math.py
            pymc/tests/distributions/test_transform.py
            pymc/tests/sampling/test_mcmc.py
            pymc/tests/sampling/test_parallel.py
            pymc/tests/test_printing.py

          - |
            pymc/tests/distributions/test_timeseries.py
            pymc/tests/gp/test_cov.py
            pymc/tests/gp/test_gp.py
            pymc/tests/gp/test_mean.py
            pymc/tests/gp/test_util.py
            pymc/tests/test_model.py
            pymc/tests/test_model_graph.py
            pymc/tests/ode/test_ode.py
            pymc/tests/ode/test_utils.py
            pymc/tests/step_methods/hmc/test_quadpotential.py

          - |
            pymc/tests/logprob/test_abstract.py
            pymc/tests/logprob/test_censoring.py
            pymc/tests/logprob/test_composite_logprob.py
            pymc/tests/logprob/test_cumsum.py
            pymc/tests/logprob/test_joint_logprob.py
            pymc/tests/logprob/test_mixture.py
            pymc/tests/logprob/test_rewriting.py
            pymc/tests/logprob/test_scan.py
            pymc/tests/logprob/test_tensor.py
            pymc/tests/logprob/test_transforms.py
            pymc/tests/logprob/test_utils.py

      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test
          channel-priority: strict
          environment-file: conda-envs/environment-test.yml
          python-version: ${{matrix.python-version}}
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        run: |
          conda activate pymc-test
          python -m pytest -vv --cov=pymc --cov-report=xml --no-cov-on-fail --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  windows:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float64]
        python-version: ["3.8"]
        test-subset:
          - pymc/tests/variational/test_approximations.py pymc/tests/variational/test_callbacks.py pymc/tests/variational/test_inference.py pymc/tests/variational/test_opvi.py pymc/tests/test_initial_point.py
          - pymc/tests/test_model.py pymc/tests/step_methods/test_compound.py pymc/tests/step_methods/hmc/test_hmc.py
          - pymc/tests/gp/test_cov.py pymc/tests/gp/test_gp.py pymc/tests/gp/test_mean.py pymc/tests/gp/test_util.py pymc/tests/ode/test_ode.py pymc/tests/ode/test_utils.py pymc/tests/smc/test_smc.py pymc/tests/sampling/test_parallel.py
          - pymc/tests/sampling/test_mcmc.py pymc/tests/step_methods/test_metropolis.py pymc/tests/step_methods/test_slicer.py pymc/tests/step_methods/hmc/test_nuts.py

      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=core2'
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-envs/windows-environment-test.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/windows-environment-test.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test
          channel-priority: strict
          environment-file: conda-envs/windows-environment-test.yml
          python-version: ${{matrix.python-version}}
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        # This job uses a cmd shell, therefore the environment variable syntax is different!
        # The ">-" in the next line replaces newlines with spaces (see https://stackoverflow.com/a/66809682).
        run: >-
          conda activate pymc-test &&
          python -m pytest -vv --cov=pymc --cov-report=xml --no-cov-on-fail --cov-report term --durations=50 %TEST_SUBSET%
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  macos:
    strategy:
      matrix:
        os: [macos-latest]
        floatx: [float64]
        python-version: ["3.9"]
        test-subset:
          - |
            pymc/tests/sampling/test_parallel.py
            pymc/tests/test_data.py
            pymc/tests/test_model.py

          - |
            pymc/tests/sampling/test_mcmc.py

          - |
            pymc/tests/backends/test_arviz.py
            pymc/tests/variational/test_updates.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test
          channel-priority: strict
          environment-file: conda-envs/environment-test.yml
          python-version: ${{matrix.python-version}}
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pymc
        run: |
          conda activate pymc-test
          pip install -e .
          python --version
      - name: Run tests
        run: |
          python -m pytest -vv --cov=pymc --cov-report=xml --no-cov-on-fail --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  jax:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        floatx: [float64]
        python-version: ["3.9"]
        test-subset:
          - pymc/tests/sampling/test_jax.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment-test.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-test.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test
          channel-priority: strict
          environment-file: conda-envs/environment-test.yml
          python-version: ${{matrix.python-version}}
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install pymc
        run: |
          conda activate pymc-test
          pip install -e .
          python --version
      - name: Install jax specific dependencies
        run: |
          conda activate pymc-test
          pip install "numpyro>=0.8.0"
          pip install git+https://github.com/blackjax-devs/blackjax.git@0.7.0
      - name: Run tests
        run: |
          python -m pytest -vv --cov=pymc --cov-report=xml --no-cov-on-fail --cov-report term --durations=50 $TEST_SUBSET
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: TEST_SUBSET
          name: JAX tests - ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
  float32:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float32]
        python-version: ["3.10"]
        test-subset:
        - pymc/tests/sampling/test_mcmc.py pymc/tests/ode/test_ode.py pymc/tests/ode/test_utils.py
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=core2'
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if conda-envs/windows-environment-test.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-py${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/windows-environment-test.yml') }}
      - name: Cache multiple paths
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
            hashFiles('requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          activate-environment: pymc-test
          channel-priority: strict
          environment-file: conda-envs/windows-environment-test.yml
          python-version: ${{matrix.python-version}}
          use-mamba: true
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Install-pymc
        run: |
          conda activate pymc-test
          pip install -e .
          pip install --pre -U polyagamma
          python --version
      - name: Run tests
        # This job uses a cmd shell, therefore the environment variable syntax is different!
        # The ">-" in the next line replaces newlines with spaces (see https://stackoverflow.com/a/66809682).
        run: >-
          conda activate pymc-test &&
          python -m pytest -vv --cov=pymc --cov-report=xml --no-cov-on-fail --cov-report term --durations=50 %TEST_SUBSET%
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: TEST_SUBSET
          name: ${{ matrix.os }} ${{ matrix.floatx }}
          fail_ci_if_error: false
