name: arviz-compatibility

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pytest:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float64]
        test-subset:
          - pymc3/tests/test_distributions_random.py
          - pymc3/tests/test_sampling.py
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      THEANO_FLAGS: floatX=${{ matrix.floatx }},gcc.cxxflags='-march=core2'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if conda-envs/environment-dev-py37.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('conda-envs/environment-dev-py37.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          channel-priority: strict
          environment-file: conda-envs/environment-dev-py37.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: |
          conda activate testenv
          conda remove arviz -y
          pip install git+git://github.com/arviz-devs/arviz.git
          python -m pytest -vv --cov=pymc3 --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
